spring:
  application:
    name: ms-customer-orchestration
  cloud:
    kubernetes:
      reload:
        enabled: true
  main:
    banner-mode: off
  security:
    oauth2:
      client:
        registration:
          auth0:
            authorization-grant-type: client_credentials
            client-id: dummy-value
            client-secret: dummy-value
            scope: read:customer,create:customer
        provider:
          auth0:
            token-uri: https://qwyck.eu.auth0.com/oauth/token

openapi:
  title: Customer Orchestration
  description: Customer Orchestration API
  version: 1.0.1